// <auto-generated />
namespace Docitcare_v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Created_Table_SuperUserLogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Created_Table_SuperUserLogin));
        
        string IMigrationMetadata.Id
        {
            get { return "202108311939176_Created_Table_SuperUserLogin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
