// <auto-generated />
namespace Docitcare_v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Create_Arole_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_Arole_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202108101757438_Create_Arole_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
